# Generated by Django 2.0.1 on 2019-08-20 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostelAdmin', '0007_auto_20190820_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelAdmin.Hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('avg', models.DecimalField(decimal_places=1, default='0.0', max_digits=20)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelAdmin.Hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=25)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('user_name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('contact', models.CharField(blank=True, max_length=250, null=True)),
                ('user_type', models.CharField(choices=[('S', 'Student'), ('O', 'Hostel_Owner')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.User'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.User'),
        ),
        migrations.AddField(
            model_name='hostelowner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.User'),
        ),
    ]
